name = "serverless-qrcode-hub"
main = "index.js"
compatibility_date = "2025-03-10"

[[d1_databases]]
binding = "DB"
database_name = "qrcode_hub"
# 注意：将下面的 id 替换为你自己拷贝的 D1 存储的 id 才能正常使用！
database_id = "d7bf06f464c943b4bf085dc1e0b39093"

[triggers]
crons = ["0 2 */1 * *"]

[[env.dev.d1_databases]]
binding = "DB"
database_name = "qrcode_hub_dev"
database_id = "2e092e8a3a0b432fb21a148ebe119d41

[env.dev.triggers]
crons = ["*/10 * * * * *"]

[assets]
directory = "./dist"
binding = "ASSETS"
